server:
  port: 12306

log:
  path: K:\lanhanhua\logs
  file: mylog.log


spring:
  application:
    name: reportMingzi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.36.8:7999/fans_growing
    username: root
    password: zdf_db_admin

mybatis:
  type-aliases-package: com.course.demo.model
#  config.path: mybatis-config.xml
  mapper-locations:
    - mapper/*
